[book]
title = "Le Lycée des Routes"
authors = "Emmanuel Bosquet"
description = "une nouvelle initiatique"
multilingual = false
# src = "../src"
language = "fr"

[build]
build-dir = "../web-book"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/Keksoj/lyceedesroutes"
