[book]
title = "Le Lycée des Routes"
authors = "Emmanuel Bosquet"
description = "une nouvelle initiatique"
multilingual = false
src = "src"
language = "fr"

[output.html]
additional-css = ["mdbook/cursom.css"]
git-repository-url = "https://github.com/Keksoj/lyceedesroutes"
