#!/usr/bin/env bash

usage() {
    cat 1>&2 <<EOF
exporter le Lycée des Routes

USAGE:
    export [COMMANDE]

COMMANDES
    web             (ré)exporte la version web du livre avec mdbook
    epub            (ré)exporte l'epub
    pdf             (ré)exporte le PDF
    latex           (ré)exporte le fichier latex (débugage)
    help            Affiche ce message
EOF
}

main() {
    case "$1" in
    web)
        web
        ;;
    epub)
        epub
        ;;
    pdf)
        pdf
        ;;
    help)
        usage
        ;;
    *)
        echo "Besoin d'un argument valide"
        usage
        ;;
    esac
}

check_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Veuillez installer $1"
        exit 1
    fi
}

web() {
    check_cmd mdbook

    git pull

    cp -v src/* mdbook/src/
    mdbook build mdbook
}

epub() {
    check_cmd pandoc

    pandoc --data-dir=epub \
        --toc-depth=1 \
        epub/metadata.yaml \
        src/* \
        --output exports/lelyceedesroutes.epub
}

pdf() {
    check_cmd pandoc

    echo "Pandoc calls for aid!"

    pandoc latex/pagetitre.md \
        src/* \
        --verbose --top-level-division=chapter \
        --variable=indent \
        --template=latex/template.tex \
        --standalone --output exports/lelyceedesroutes.tex

    check_cmd pdflatex
    echo "pdflatex will respond!"
    cd exports
    pdflatex lelyceedesroutes.tex
}


main "$1" || exit 1
